### ISSUE TITLE
Remember/lock TT-RSS URL

### ISSUE THREAD

**Issue by nodiscc** [kucrut/ttrss-reader#11]
Hi, my ttrss-reader installation is at https://my.domain.tld/reader and my TT-RSS installation at https://my.domain.tld/tt-rss. Everytime I login to tt-rss reader, the URL field is autofilled to https://my.domain.tld/ , I have to change it manually to include the directory name (unfortunately browser username/password saving mechanism does not remember/autofill the URL.)

Can it be done so that ttrss-reader reads the URL from a config file on the server? And uses it as default, or locks it to the value defined in the file.

Thanks

**Comment by kucrut** [comment]
@nodiscc This is implemented in [version 0.4.0](https://github.com/kucrut/ttrss-reader/releases/tag/v0.4.0).

**Comment by nodiscc** [comment]
@kucrut thanks!

The latest release was tagged `1.2.1`. Is there a reason why the new release is `0.4.0` (lower number)?

**Comment by kucrut** [comment]
Oh dear 😂
It's fixed now. The newest release is tagged `v1.3.0`. Thank you for letting me know 💯
