### ISSUE TITLE
buttons are too close

### ISSUE THREAD

**Issue by 2vek** [kucrut/ttrss-reader#3]
when using on tablet and phone, 
- accidentally tapping logout button when tapping settings button
- accidentally tapping "mark all as read" when tapping refresh button on a feed with dozens of unread feeds.

can happen and both are annoying on touch based devices.

I think margin of 1.5em or 2em between them would be better. There is no shortage of white space in UI after all.

**Comment by kucrut** [comment]
Done in https://github.com/kucrut/ttrss-reader/commit/2f30d9d270f052bc82e69bf163af4bcf05f62de5
